### ISSUE TITLE
Basic Examples for Editing, Adding and deleting entries from the database.

### ISSUE THREAD

**Issue by BharatKalluri** [sru-systems/rust-kpdb#1]
Hey @mrijkeboer,

Please Mention a simple example detailing how to edit, add and delete entries from the KeePass DB and how to save the database.I have been trying to understand by looking at the source code but was unsuccessful. For reference, [This](https://github.com/pschmitt/pykeepass#simple-example) is a great example.

Thanks for the library, fantastic work!

Cheers!

**Comment by mrijkeboer** [comment]
Hi @BharatKalluri,

Sorry for taking so long to respond, I've been quite busy lately. I primarily use this library to read existing databases and therefore modifying databases was not really user friendly. I've just pushed a new version (0.3.0) to [crates.io](https://crates.io/crates/rust-kpdb) that adds several functions to make modifying easier. Please check the documentation for the [Database](https://docs.sru-systems.com/rust-kpdb/0.3.0/kpdb/struct.Database.html), [Entry](https://docs.sru-systems.com/rust-kpdb/0.3.0/kpdb/struct.Entry.html) and [Group](https://docs.sru-systems.com/rust-kpdb/0.3.0/kpdb/struct.Group.html) structs for more info on those functions. I've also expanded the examples in the README a bit.

**Comment by BharatKalluri** [comment]
I was making a KeePass GTK client for Linux. I tried contacting you but could'nt. So I had to rewrite everything in python. [This](https://github.com/BharatKalluri/Easypass) was the project I am referring to. Now that writing is supported, I am super excited to rewrite the project entirely in Rust. The examples look great, it would be better if you could just drop in an example as to how editing of works in README. 

Thanks!
