### ISSUE TITLE
Set the creation time of an item

### ISSUE THREAD

**Issue by miracle2k** [sru-systems/rust-kpdb#2]
I want to use this library to import from a different format to KeePass. I'd like to keep the creation times. Being new to Rust, I am not sure if this is my mistake, but I can't seem to figure out how to set the creation date:

```
error[E0603]: module `types` is private
  --> src/main.rs:15:5
   |
15 | use kpdb::types::times::Times;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^
```

and

```
error[E0599]: no method named `set_creation_time` found for type `kpdb::Entry` in the current scope
  --> src/main.rs:55:15
   |
55 |         entry.set_creation_time(utc);
   |               ^^^^^^^^^^^^^^^^^
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope, perhaps add a `use` for it:
   |
9  | use kpdb::types::times::Times;
   |
```

Any suggestions?

**Comment by mrijkeboer** [comment]
Hi @miracle2k,

Like explained in the commit message of d2e1344 I forgot to export the Times trait. I just pushed version 0.4.0, that fixes this problem, to crates.io.

**Comment by miracle2k** [comment]
That works great, thanks!
