### ISSUE TITLE
Get parent of an Entry or Group

### ISSUE THREAD

**Issue by ghosty141** [sru-systems/rust-kpdb#5]
Hi,
is there a way to get the parent Group of an Entry or a Group? Right now I don't really see a way to find the parent of a group without having to go through all entries and check where the UUID matches.

Is this even possible?

**Comment by ghosty141** [comment]
I implemented this in pull request #6. This can be closed if it gets merged.

**Comment by mrijkeboer** [comment]
I merged #6.
